{
 "title": "traqueur_dashboard",
 "time": { "from": "now-15m", "to": "now-10s" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource_traqueur", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "General informations, latency, activity type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Informations",
   "type": "table",
   "description": "- Information collected 1 hour ago at max",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with information_panel as (\n(SELECT \n'Collection time : ' ||  to_char(dtcol, 'YYYY/MM/DD HH24:MI:SS') as collection_time,\n'Hostname : ' || cluster_hostname as hostname,\n'Cluster version : '|| cluster_postgres_version as version,\n'Cluster port : '|| cluster_port as port,\n'WAL archiving : '|| cluster_archive_mode as archive_mode,\n'Number of processes : '|| cluster_processes as processes,\n'Shared buffers size : '|| cluster_shared_buffers as shared_buffers,\n'Cluster size : '|| cluster_pretty_size as cluster_size,\n'Databases : '|| cluster_databases as databases,\n'Description : '|| cluster_comment as comment\n from traqueur_cluster_information where $__timeFilter(dtcol) order by dtcol desc fetch first 1 rows only)\n)\nselect unnest(array[collection_time, hostname, comment, version, port, processes, archive_mode, shared_buffers, cluster_size, databases]) as \"Informations\" from information_panel\n"
    }
   ]
  },
  {
   "title": "IO latency informations",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with haut as (select dtcol, context, read_time, reads, write_time, writes, writeback_time, writebacks, extends, extend_time, fsync_time, fsyncs, evictions, stats_reset  from traqueur_io_stats where dtcol = (select max(dtcol) from traqueur_io_stats where $__timeFilter(dtcol))),\nbas as (select dtcol, context, read_time, reads, write_time, writes, writeback_time, writebacks, extends, extend_time, fsync_time, fsyncs, evictions, stats_reset from traqueur_io_stats where dtcol = (select min(dtcol) from traqueur_io_stats where $__timeFilter(dtcol)))\nselect  haut.context, \ncase when (sum(haut.reads)-sum(bas.reads)) <> 0 then round(((sum(haut.read_time)-sum(bas.read_time))/(sum(haut.reads)-sum(bas.reads)))::numeric,2) else null end \"Reads latency (ms)\", \ncase when (sum(haut.writes)-sum(bas.writes)) <> 0 then round(((sum(haut.write_time)-sum(bas.write_time))/(sum(haut.writes)-sum(bas.writes)))::numeric,2) else null end \"Writes latency (ms)\", \ncase when (sum(haut.writebacks)-sum(bas.writebacks)) <> 0 then round(((sum(haut.writeback_time)-sum(bas.writeback_time))/(sum(haut.writebacks)-sum(bas.writebacks)))::numeric,2) else null end \"Writebacks latency (ms)\", \ncase when (sum(haut.extends)-sum(bas.extends)) <> 0 then round(((sum(haut.extend_time)-sum(bas.extend_time))/(sum(haut.extends)-sum(bas.extends)))::numeric,2) else null end \"Extends latency (ms)\", \ncase when (sum(haut.fsyncs)-sum(bas.fsyncs)) <> 0 then round(((sum(haut.fsync_time)-sum(bas.fsync_time))/(sum(haut.fsyncs)-sum(bas.fsyncs)))::numeric,2) else null end \"Fsyncs latency (ms)\",\n sum(haut.evictions)-sum(bas.evictions)  \"Evictions\"\n from haut join bas on (haut.context = bas.context) \n where haut.stats_reset = bas.stats_reset \n group by haut.context order by haut.context asc;"
    }
   ]
  },
  {
   "title": "NON CPU activity",
   "type": "gauge",
   "description": "- last 5 minutes",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(dtcol),\n  100 - pourcentage_cpu as \"non_cpu_activity\"\nFROM\n  traqueur_sessions_actives\nWHERE\n   $__timeFilter(dtcol) and datid is not null\n  \n"
    }
   ]
  },
  {
   "title": "Current activity (pids, applications, queries)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active sessions *",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  dtcol as \"time\",\n  count(*)-1 as \"active processes\"\nFROM\n  traqueur_sessions_actives\nWHERE\n   $__timeFilter(dtcol)\n  group by dtcol\norder by dtcol\n\n  \n\n"
    }
   ]
  },
  {
   "title": "Current PIDs & applications",
   "type": "table",
   "description": "- top 10\n- last completed minute of collection within the last 5 minutes",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with collecte_complete(derniere) as (select date_trunc('minute', max(dtcol) - interval '1 minute') from traqueur_sessions_actives where  $__timeFilter(dtcol))\nSELECT datname as \"database\", pid, application, detections from\n(SELECT date_trunc('minute', dtcol) as \"time\", datname, pid, coalesce(application_info->>'program', application_name) as application, count(*) as detections\nFROM traqueur_sessions_actives\nwhere $__timeFilter(dtcol) and date_trunc('minute', dtcol) = (select derniere from collecte_complete) and datid is not null\ngroup by date_trunc('minute', dtcol),  pid, application_info->>'program', application_name, datname\nFETCH FIRST 10 ROWS ONLY) r\norder by detections desc"
    }
   ]
  },
  {
   "title": "Current applications & queries",
   "type": "table",
   "description": "- top 10\n- last completed minute of collection within the last 5 minutes",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with collecte_complete(derniere) as (select date_trunc('minute', max(dtcol) - interval '1 minute') from traqueur_sessions_actives where  $__timeFilter(dtcol))\nSELECT datname as \"database\", application, query, detections, distinct_exe from\n(SELECT date_trunc('minute', dtcol) as \"time\", datname, coalesce(application_info->>'program', application_name) as \"application\", coalesce(tquery, query) as \"query\", count(*) as detections, count(distinct query_start) as distinct_exe\nFROM traqueur_sessions_actives\nwhere  $__timeFilter(dtcol) and date_trunc('minute', dtcol) = (select derniere from collecte_complete) and datid is not null\ngroup by date_trunc('minute', dtcol),  coalesce(tquery, query), application_info->>'program', application_name,datname\nFETCH FIRST 10 ROWS ONLY) r\norder by detections desc"
    }
   ]
  },
  {
   "title": "Current PIDs & queries",
   "type": "table",
   "description": "- top 10\n- last completed minute of collection within the last 5 minutes",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with collecte_complete(derniere) as (select date_trunc('minute', max(dtcol) - interval '1 minute') from traqueur_sessions_actives where $__timeFilter(dtcol))\nSELECT datname as \"database\", pid, query, detections, distinct_exe from\n(SELECT date_trunc('minute', dtcol) as \"time\", datname, pid, coalesce(tquery, query) as \"query\", count(*) as detections, count(distinct query_start) as distinct_exe\nFROM traqueur_sessions_actives\nwhere $__timeFilter(dtcol) and date_trunc('minute', dtcol) = (select derniere from collecte_complete) and datid is not null\ngroup by date_trunc('minute', dtcol),  coalesce(tquery, query), pid, datname\nFETCH FIRST 10 ROWS ONLY) r\norder by detections desc"
    }
   ]
  },
  {
   "title": "Current waits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current wait event types",
   "type": "barchart",
   "description": "- last completed minute of collection within the last 5 minutes",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "with collecte_complete(derniere) as (select date_trunc('minute', max(dtcol) - interval '1 minute') from traqueur_sessions_actives where  $__timeFilter(dtcol))\nSELECT time, wait_event_type as \"metric\", detections from\n(SELECT date_trunc('minute', dtcol) as \"time\", coalesce(wait_event_type, 'CPU or ?') as \"wait_event_type\", count(*) as detections\nFROM traqueur_sessions_actives\nWHERE  $__timeFilter(dtcol) and date_trunc('minute', dtcol) = (select derniere from collecte_complete) and datid is not null\ngroup by date_trunc('minute', dtcol),  coalesce(wait_event_type, 'CPU or ?')\nFETCH FIRST 5 ROWS ONLY) r\norder by detections desc"
    }
   ]
  },
  {
   "title": "Current wait event types",
   "type": "table",
   "description": "- top 10\n- last completed minute of collection within the last 5 minutes",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with collecte_complete(derniere) as (select date_trunc('minute', max(dtcol) - interval '1 minute') from traqueur_sessions_actives where  $__timeFilter(dtcol))\nSELECT datname as \"database\", wait_event_type, detections from\n(SELECT datname, date_trunc('minute', dtcol) as \"time\", coalesce(wait_event_type, 'CPU or ?') as \"wait_event_type\", count(*) as detections\nFROM traqueur_sessions_actives\nWHERE  $__timeFilter(dtcol) and date_trunc('minute', dtcol) = (select derniere from collecte_complete) and datid is not null\ngroup by date_trunc('minute', dtcol),  coalesce(wait_event_type, 'CPU or ?'), datname\nFETCH FIRST 10 ROWS ONLY) r\norder by detections desc"
    }
   ]
  },
  {
   "title": "Current wait event types & queries",
   "type": "table",
   "description": "- top 10\n- last completed minute of collection within the last 5 minutes",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with collecte_complete(derniere) as (select date_trunc('minute', max(dtcol) - interval '1 minute') from traqueur_sessions_actives where $__timeFilter(dtcol))\nSELECT datname as \"database\", wait_event_type, query, detections, distinct_exe from\n(SELECT datname, date_trunc('minute', dtcol) as \"time\", coalesce(tquery, query) as \"query\", coalesce(wait_event_type, 'CPU or ?') as \"wait_event_type\", count(*) as detections, count(distinct query_start) as distinct_exe\nFROM traqueur_sessions_actives\nwhere $__timeFilter(dtcol) and date_trunc('minute', dtcol) = (select derniere from collecte_complete) and datid is not null\ngroup by date_trunc('minute', dtcol),  coalesce(tquery, query), coalesce(wait_event_type, 'CPU or ?'), datname\nFETCH FIRST 10 ROWS ONLY) r\norder by detections desc"
    }
   ]
  },
  {
   "title": "Locks : blocked pids & blockers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocked sessions *",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(dtcol),\n  count(*) as \"blocked sessions\"\nFROM\n  traqueur_sessions_actives\nWHERE\n$__timeFilter(dtcol) and datid is not null and blockers is not null\n  group by dtcol\norder by dtcol\n\n  \n\n"
    }
   ]
  },
  {
   "title": "Blocked pids & final blockers",
   "type": "table",
   "description": "- blocked/blockers by minute within the last 5 minutes",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', dtcol) as \"time\", array_agg(distinct pid) as \"blocked pids\",  blockers as blockers from traqueur_sessions_actives where  $__timeFilter(dtcol) and blockers is not null group by time, blockers order by \"time\" desc"
    }
   ]
  },
  {
   "title": "Global charge *",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with tentatives(nb) as (select count(*) from traqueur_sessions_actives where $__timeFilter(dtcol) and datid is null),\nstats as (select datname, min(extract (epoch from dtcol)) mindtcol, max(extract (epoch from dtcol)) maxdtcol, min(xact_commit) mincom, min(xact_rollback) minrol, max(xact_commit) maxcom, max(xact_rollback) maxrol from traqueur_cluster_stats where $__timeFilter(dtcol) and not $__timeFilter(stats_reset) group by datname),\ncommitted_transactions as (select (sum(maxcom)-sum(mincom))/(min(maxdtcol)-min(mindtcol)) as committed_transactions_by_sec from stats),\nrolled_back_transactions as (select (sum(maxrol)-sum(minrol))/(min(maxdtcol)-min(mindtcol)) as rolled_back_transactions_by_sec from stats)\nSELECT\n   count(*) as detections, \n   count(distinct query_start) as distinct_exe, \n   (count(*)::real/(select nb from tentatives)) as average_active_sessions, \n   (select committed_transactions_by_sec from committed_transactions) as committed_transactions_by_sec,\n   (select rolled_back_transactions_by_sec from rolled_back_transactions) as rolled_back_transactions_by_sec\nFROM\n  traqueur_sessions_actives\nWHERE\n   $__timeFilter(dtcol) and datid is not null\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Global charge and top queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Queries *",
   "type": "table",
   "description": "- top 100",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n   datname || ' - ' || case when length(coalesce(application_info->>'program', application_name , '')) = 0 then '?' else coalesce(application_info->>'program', application_name) end || ' - ' || to_hex(coalesce(itquery, iquery)) || ' - ' || coalesce(tquery, query) as metric, count(*) as detections, count(distinct query_start) as distinct\nFROM\n  traqueur_sessions_actives\nWHERE\n   $__timeFilter(dtcol) and datid is not null\ngroup by metric\norder by detections desc\nfetch first 1000 rows only \n\n\n\n"
    }
   ]
  },
  {
   "title": "Top waits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top wait event types *",
   "type": "table",
   "description": "- by hour",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with tsa_agg as (select min(dtcol) as mindtcol, date_trunc('hour', dtcol) as dtrunc, wait_event_type, count(*)  as detections\nFROM\n  traqueur_sessions_actives\nWHERE \n   $__timeFilter(dtcol) and datid is not null\ngroup by dtrunc, wait_event_type)\nselect case when dtrunc  < (select min(mindtcol) from tsa_agg) then (select min(mindtcol) from tsa_agg) else dtrunc end as \"time\", \n       coalesce(wait_event_type, 'CPU or ?') as metric,\n       detections\nfrom tsa_agg\norder by \"time\" desc, detections desc;\n\n\n"
    }
   ]
  },
  {
   "title": "Top wait events *",
   "type": "table",
   "description": "- top 100",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT coalesce(wait_event_type || ' - ' || wait_event, 'CPU or ?') as metric,\n  count(*) as detections\n  from traqueur_sessions_actives\nwhere $__timeFilter(dtcol) and datid is not null\ngroup by metric\norder by count(*) desc\nFETCH FIRST 100 ROWS ONLY"
    }
   ]
  },
  {
   "title": "Top queries & wait events *",
   "type": "table",
   "description": "- top 1000",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  datname as \"database\", to_hex(coalesce(itquery, iquery)) as hquery, coalesce(tquery, query) as query, coalesce(wait_event_type || ' - ' || wait_event, 'CPU or ?') as metric,\n  count(*) as detections\n  from traqueur_sessions_actives\nwhere $__timeFilter(dtcol) and datid is not null\ngroup by to_hex(coalesce(itquery, iquery)), coalesce(tquery, query), metric, datname\norder by count(*) desc\nFETCH FIRST 1000 ROWS ONLY"
    }
   ]
  },
  {
   "title": "CPU load & IO waits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU load",
   "type": "gauge",
   "description": "- current cpu load excluding traqueur",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 139 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(dtcol),\n  pourcentage_cpu\nFROM\n  traqueur_sessions_actives\nWHERE\n    $__timeFilter(dtcol) and datid is null\norder by dtcol\n\n  \n"
    }
   ]
  },
  {
   "title": "CPU activity & IO waits system wide",
   "type": "barchart",
   "description": "- Last 5 minutes",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 139 },
   "targets": [
    {
     "rawSql": "with vals_deb as (select dtcol, user_traqueur, system_traqueur, idle_traqueur, iowait_traqueur from traqueur_times where dtcol = (select min(dtcol) from traqueur_times where $__timeFilter(dtcol))),\nvals_fin as (select  dtcol, user_traqueur, system_traqueur, idle_traqueur, iowait_traqueur from traqueur_times where dtcol = (select max(dtcol) from traqueur_times where $__timeFilter(dtcol)))\nselect \nvals_fin.dtcol as \"time\",\ngreatest(round(vals_fin.user_traqueur - vals_deb.user_traqueur),0) as \"CPU user time (s)\",\ngreatest(round(vals_fin.system_traqueur - vals_deb.system_traqueur),0) as \"CPU system time (s)\",\nCASE when (select upper(cluster_os_family) from traqueur_cluster_information where cluster_os_family is not null fetch first 1 row only) like '%LINUX%' THEN greatest(round(vals_fin.iowait_traqueur - vals_deb.iowait_traqueur),0) ELSE null END AS \"IO wait (s)\",\ngreatest(round(vals_fin.idle_traqueur - vals_deb.idle_traqueur),0) as \"CPU idle time (s)\"\nfrom vals_deb, vals_fin;\n"
    }
   ]
  },
  {
   "title": "CPU load *",
   "type": "timeseries",
   "description": "- cpu load excluding traqueur",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(dtcol),\n  pourcentage_cpu as \"CPU load\"\nFROM\n  traqueur_sessions_actives\nWHERE\n   $__timeFilter(dtcol)  and datid is null\norder by dtcol\n  \n\n"
    }
   ]
  },
  {
   "title": "CPU & IO times *",
   "type": "table",
   "description": "- by hour",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 161 },
   "targets": [
    {
     "rawSql": "with vals_deb as (select min(dtcol) as mindtcol, date_trunc('hour', dtcol) as dtcol_h,  min(user_traqueur) as user_traqueur, min(system_traqueur) as system_traqueur, min(idle_traqueur) as idle_traqueur, min(iowait_traqueur) as iowait_traqueur from traqueur_times where $__timeFilter(dtcol) group by date_trunc('hour', dtcol)),\nvals_fin as (select date_trunc('hour', dtcol)  as dtcol_h, max(user_traqueur) as user_traqueur, max(system_traqueur) as system_traqueur, max(idle_traqueur) as idle_traqueur, max(iowait_traqueur) as iowait_traqueur from traqueur_times where $__timeFilter(dtcol) group by date_trunc('hour', dtcol))\nselect  \ncase when dtcol_h > (select min(vals_deb.mindtcol) from vals_deb) then vals_deb.dtcol_h else vals_deb.mindtcol end as \"time\", \ngreatest(round(vals_fin.user_traqueur - vals_deb.user_traqueur),0) as \"CPU_user_time\",\ngreatest(round(vals_fin.system_traqueur - vals_deb.system_traqueur),0) as \"CPU_system_time\",\nCASE when (select upper(cluster_os_family) from traqueur_cluster_information fetch first 1 row only) like '%LINUX%' THEN greatest(round(vals_fin.iowait_traqueur - vals_deb.iowait_traqueur), 0) ELSE null END AS \"IO_wait\",\ngreatest(round(vals_fin.idle_traqueur - vals_deb.idle_traqueur),0) as \"CPU_idle_time\"\nfrom vals_deb join vals_fin using (dtcol_h) order by \"time\" desc;"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory (MB)",
   "type": "stat",
   "description": "- sum of memory used by current postgresql active processes excluding traqueur",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(dtcol),\n  sum(mem)/1024/1024\nFROM\n  traqueur_sessions_actives\nWHERE\n  $__timeFilter(dtcol) and datid is not null\ngroup by dtcol\norder by dtcol desc\nfetch first 1 row only \n\n  \n"
    }
   ]
  },
  {
   "title": "Memory (mb) *",
   "type": "timeseries",
   "description": "Total memory used by postgresql active processes, excluding traqueur ones",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(dtcol),\n  sum(mem)/1024/1024 as \"Memory\"\nFROM\n  traqueur_sessions_actives \nWHERE\n    $__timeFilter(dtcol) and datid is not null\n  group by dtcol\norder by dtcol\n\n  \n\n"
    }
   ]
  },
  {
   "title": "Swapped memory (MB)",
   "type": "stat",
   "description": "- sum of memory swapped by current postgresql active processes, excluding traqueur",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(dtcol),\n  sum(swapped)/1024/1024\nFROM\n  traqueur_sessions_actives\nWHERE\n  $__timeFilter(dtcol) and datid is not null\ngroup by dtcol\norder by dtcol desc\nfetch first 1 row only "
    }
   ]
  },
  {
   "title": "Swapped memory (mb) *",
   "type": "timeseries",
   "description": "Total swapped memory used by postgresql active processes, excluding traqueur ones",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(dtcol),\n  sum(swapped)/1024/1024 as \"Swapped memory\"\nFROM\n  traqueur_sessions_actives\nWHERE\n  $__timeFilter(dtcol) and datid is not null\n  group by dtcol\norder by dtcol\n\n\n  \n\n"
    }
   ]
  }
 ]
}